In [ ]:
from os import listdir
from os.path import isfile, join

In [ ]:
onlyfiles = [f for f in listdir("/content/drive/MyDrive/dataset/classic punk") if isfile(join("/content/drive/MyDrive/dataset/classic punk", f))]
onlyfiles.sort(key=lambda v: v.upper())
matching = [s for s in onlyfiles if "lyrics.csv" in s]
onlyfiles.remove(matching[0])
onlyfiles

['Agent Orange - Bloodstains - Original Version.mp3',
 'Bad Brains - Banned In D.C..mp3',
 "Bad Brains - Sailin' On.mp3",
 'Black Flag - Rise Above.mp3',
 'Black Flag - Six Pack.mp3',
 'Black Flag - TV Party.mp3',
 "Buzzcocks - Ever Fallen in Love (With Someone You Shouldn't've) - 1996 Remastered Version.mp3",
 'Dead Boys - Sonic Reducer.mp3',
 'Dead Kennedys - California Uber Alles.mp3',
 'Dead Kennedys - Holiday in Cambodia.mp3',
 'Descendents - Hope.mp3',
 'Descendents - Suburban Home.mp3',
 'DEVO - Gut Feeling  (Slap Your Mammy).mp3',
 'DEVO - Uncontrollable Urge.mp3',
 'Fugazi - Bad Mouth.mp3',
 'Fugazi - Waiting Room.mp3',
 'Gang Of Four - Damaged Goods.mp3',
 'Germs - Lexicon Devil.mp3',
 "Hüsker Dü - Don't Want to Know If You Are Lonely.mp3",
 'Iggy Pop - Lust For Life.mp3',
 'Joy Division - Disorder - 2007 Remaster.mp3',
 "Joy Division - She's Lost Control - 2007 Remaster.mp3",
 'Minor Threat - Minor Threat.mp3',
 'Minor Threat - Salad Days.mp3',
 'Minutemen - Corona.mp3',
 'Minutemen - Viet Nam.mp3',
 'Misfits - Last Caress - C.I. Recording 1978.mp3',
 'Misfits, Glenn Danzig - Where Eagles Dare.mp3',
 'Pavement - Harness Your Hopes - (B-side).mp3',
 'Ramones - Blitzkrieg Bop - 2001 Remastered Version.mp3',
 'Ramones - I Wanna Be Sedated.mp3',
 'Richard Hell - Blank Generation.mp3',
 'Sex Pistols - Anarchy in the U.K..mp3',
 'Sex Pistols - God Save the Queen.mp3',
 'Sex Pistols - Pretty Vacant.mp3',
 'Stiff Little Fingers - Alternative Ulster.mp3',
 'Stiff Little Fingers - Suspect Device.mp3',
 'Suicidal Tendencies - Institutionalized.mp3',
 'T.S.O.L. - Code Blue.mp3',
 'Television - Marquee Moon.mp3',
 'The Clash - I Fought the Law.mp3',
 'The Clash - London Calling - Remastered.mp3',
 'The Cramps - Human Fly.mp3',
 "The Cramps - I Can't Hardly Stand It.mp3",
 'The Damned - New Rose.mp3',
 "The Dead Milkmen - Dean's Dream.mp3",
 'The Stooges - I Wanna Be Your Dog.mp3',
 'Violent Femmes - Blister in the Sun - 2002 Remastered Version.mp3',
 'Wire - Mannequin - 2006 Remastered Version.mp3',
 'X - Los Angeles.mp3']

In [ ]:
!pip install eyed3
import glob
import time
import eyed3
import os
import librosa

Collecting eyed3
  Downloading eyeD3-0.9.6-py3-none-any.whl (245 kB)
     |████████████████████████████████| 245 kB 14.9 MB/s
Collecting coverage[toml]<6.0.0,>=5.3.1
  Downloading coverage-5.5-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
     |████████████████████████████████| 242 kB 52.3 MB/s
Collecting deprecation<3.0.0,>=2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting filetype<2.0.0,>=1.0.7
  Downloading filetype-1.0.9-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from coverage[toml]<6.0.0,>=5.3.1->eyed3) (0.10.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from deprecation<3.0.0,>=2.1.0->eyed3) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->deprecation<3.0.0,>=2.1.0->eyed3) (3.0.6)
Installing collected packages: coverage, filetype, deprecation, eyed3
  Attempting uninstall: coverage
    Found existing installation: coverage 3.7.1
    Uninstalling coverage-3.7.1:
      Successfully uninstalled coverage-3.7.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires coverage==3.7.1, but you have coverage 5.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
coveralls 0.5 requires coverage<3.999,>=3.6, but you have coverage 5.5 which is incompatible.
Successfully installed coverage-5.5 deprecation-2.1.0 eyed3-0.9.6 filetype-1.0.9

In [ ]:
mp3s = list()
for i in onlyfiles:
    mp3s.append(glob.glob('/content/drive/MyDrive/dataset/classic punk/' + i)[0])

In [ ]:
mp3s

['/content/drive/MyDrive/dataset/classic punk/Agent Orange - Bloodstains - Original Version.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Bad Brains - Banned In D.C..mp3',
 "/content/drive/MyDrive/dataset/classic punk/Bad Brains - Sailin' On.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - Rise Above.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - Six Pack.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - TV Party.mp3',
 "/content/drive/MyDrive/dataset/classic punk/Buzzcocks - Ever Fallen in Love (With Someone You Shouldn't've) - 1996 Remastered Version.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Dead Boys - Sonic Reducer.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Dead Kennedys - California Uber Alles.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Dead Kennedys - Holiday in Cambodia.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Descendents - Hope.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Descendents - Suburban Home.mp3',
 '/content/drive/MyDrive/dataset/classic punk/DEVO - Gut Feeling  (Slap Your Mammy).mp3',
 '/content/drive/MyDrive/dataset/classic punk/DEVO - Uncontrollable Urge.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Fugazi - Bad Mouth.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Fugazi - Waiting Room.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Gang Of Four - Damaged Goods.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Germs - Lexicon Devil.mp3',
 "/content/drive/MyDrive/dataset/classic punk/Hüsker Dü - Don't Want to Know If You Are Lonely.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Iggy Pop - Lust For Life.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Joy Division - Disorder - 2007 Remaster.mp3',
 "/content/drive/MyDrive/dataset/classic punk/Joy Division - She's Lost Control - 2007 Remaster.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Minor Threat - Minor Threat.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Minor Threat - Salad Days.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Minutemen - Corona.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Minutemen - Viet Nam.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Misfits - Last Caress - C.I. Recording 1978.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Misfits, Glenn Danzig - Where Eagles Dare.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Pavement - Harness Your Hopes - (B-side).mp3',
 '/content/drive/MyDrive/dataset/classic punk/Ramones - Blitzkrieg Bop - 2001 Remastered Version.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Ramones - I Wanna Be Sedated.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Richard Hell - Blank Generation.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Sex Pistols - Anarchy in the U.K..mp3',
 '/content/drive/MyDrive/dataset/classic punk/Sex Pistols - God Save the Queen.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Sex Pistols - Pretty Vacant.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Stiff Little Fingers - Alternative Ulster.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Stiff Little Fingers - Suspect Device.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Suicidal Tendencies - Institutionalized.mp3',
 '/content/drive/MyDrive/dataset/classic punk/T.S.O.L. - Code Blue.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Television - Marquee Moon.mp3',
 '/content/drive/MyDrive/dataset/classic punk/The Clash - I Fought the Law.mp3',
 '/content/drive/MyDrive/dataset/classic punk/The Clash - London Calling - Remastered.mp3',
 '/content/drive/MyDrive/dataset/classic punk/The Cramps - Human Fly.mp3',
 "/content/drive/MyDrive/dataset/classic punk/The Cramps - I Can't Hardly Stand It.mp3",
 '/content/drive/MyDrive/dataset/classic punk/The Damned - New Rose.mp3',
 "/content/drive/MyDrive/dataset/classic punk/The Dead Milkmen - Dean's Dream.mp3",
 '/content/drive/MyDrive/dataset/classic punk/The Stooges - I Wanna Be Your Dog.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Violent Femmes - Blister in the Sun - 2002 Remastered Version.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Wire - Mannequin - 2006 Remastered Version.mp3',
 '/content/drive/MyDrive/dataset/classic punk/X - Los Angeles.mp3']

In [ ]:
mp3s = mp3s[0:20]
mp3s

['/content/drive/MyDrive/dataset/classic punk/Agent Orange - Bloodstains - Original Version.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Bad Brains - Banned In D.C..mp3',
 "/content/drive/MyDrive/dataset/classic punk/Bad Brains - Sailin' On.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - Rise Above.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - Six Pack.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Black Flag - TV Party.mp3',
 "/content/drive/MyDrive/dataset/classic punk/Buzzcocks - Ever Fallen in Love (With Someone You Shouldn't've) - 1996 Remastered Version.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Dead Boys - Sonic Reducer.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Dead Kennedys - California Uber Alles.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Dead Kennedys - Holiday in Cambodia.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Descendents - Hope.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Descendents - Suburban Home.mp3',
 '/content/drive/MyDrive/dataset/classic punk/DEVO - Gut Feeling  (Slap Your Mammy).mp3',
 '/content/drive/MyDrive/dataset/classic punk/DEVO - Uncontrollable Urge.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Fugazi - Bad Mouth.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Fugazi - Waiting Room.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Gang Of Four - Damaged Goods.mp3',
 '/content/drive/MyDrive/dataset/classic punk/Germs - Lexicon Devil.mp3',
 "/content/drive/MyDrive/dataset/classic punk/Hüsker Dü - Don't Want to Know If You Are Lonely.mp3",
 '/content/drive/MyDrive/dataset/classic punk/Iggy Pop - Lust For Life.mp3']

In [ ]:
import numpy as np
import pandas as pd
import IPython.display as ipd
import warnings
import seaborn as sns
from os import path
warnings.filterwarnings('ignore')

In [ ]:
cols = "Title Artist Album Genre y sr".split()
df = pd.DataFrame([], columns=cols)

start_time = time.process_time()


for song_path in mp3s:
    audiofile = eyed3.load(song_path)
    y , sr = librosa.load(song_path)
    df = df.append({"Title": audiofile.tag.title,
              "Artist": audiofile.tag.artist,
              "Album": audiofile.tag.album,
              "Genre": audiofile.tag.genre,
                   "y":y,
                   "sr":sr} ,ignore_index=True)

print("The whole process took", time.process_time() - start_time, "seconds.")

Non standard genre name: hardcore punk
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: early us punk
Non standard genre name: early us punk
Non standard genre name: early us punk
Non standard genre name: hardcore punk
Non standard genre name: hardcore punk
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: alternative rock
Non standard genre name: early us punk
Non standard genre name: alternative pop

The whole process took 182.459422531 seconds.

In [ ]:
df

                                                Title  ...     sr
0                      Bloodstains - Original Version  ...  22050
1                                      Banned In D.C.  ...  22050
2                                          Sailin' On  ...  22050
3                                          Rise Above  ...  22050
4                                            Six Pack  ...  22050
5                                            TV Party  ...  22050
6   Ever Fallen in Love (With Someone You Shouldn'...  ...  22050
7                                       Sonic Reducer  ...  22050
8                               California Uber Alles  ...  22050
9                                 Holiday in Cambodia  ...  22050
10                                               Hope  ...  22050
11                                      Suburban Home  ...  22050
12                    Gut Feeling / (Slap Your Mammy)  ...  22050
13                                Uncontrollable Urge  ...  22050
14                                          Bad Mouth  ...  22050
15                                       Waiting Room  ...  22050
16                                      Damaged Goods  ...  22050
17                                      Lexicon Devil  ...  22050
18               Don't Want to Know If You Are Lonely  ...  22050
19                                      Lust For Life  ...  22050

[20 rows x 6 columns]

In [ ]:
chroma=librosa.feature.chroma_cens(y=df['y'][0], sr=sr)
chroma

array([[0.35476162, 0.35729085, 0.35903907, ..., 0.20409263, 0.20189416,
        0.19960842],
       [0.46795952, 0.46744549, 0.46699618, ..., 0.22110826, 0.22024818,
        0.21956926],
       [0.27640275, 0.27258585, 0.26899749, ..., 0.40152174, 0.40570231,
        0.40947823],
       ...,
       [0.28474496, 0.28877561, 0.29231835, ..., 0.22073029, 0.22014568,
        0.21956926],
       [0.28449329, 0.28746363, 0.29013454, ..., 0.28822481, 0.29294903,
        0.29786938],
       [0.29838372, 0.30759042, 0.31585218, ..., 0.08413218, 0.09024856,
        0.09652675]])

In [ ]:
start_time = time.process_time()
chroma_means = []
chroma_stds = []

for i in range(len(df)):
  chroma=librosa.feature.chroma_cens(y=df['y'][i], sr=sr)
  chroma_mean=np.mean(chroma,axis=1)
  chroma_std=np.std(chroma,axis=1)
  chroma_means.append(chroma_mean)
  chroma_stds.append(chroma_std)

chroma_df = pd.DataFrame()
for j in range(len(df)):
  for i in range(0,12):
      chroma_df['chroma_mean_'+str(i)]=chroma_means[j][i]
  for i in range(0,12):
      chroma_df['chroma_std_'+str(i)]=chroma_means[j][i]

for t in range(len(df)):
  chroma_df.loc[t]=np.concatenate((chroma_means[t],chroma_stds[t]),axis=0)

print("The whole process took", time.process_time() - start_time, "seconds.")
chroma_df

The whole process took 74.310330736 seconds.

    chroma_mean_0  chroma_mean_1  ...  chroma_std_10  chroma_std_11
0        0.356904       0.318600  ...       0.074138       0.077196
1        0.349846       0.303398  ...       0.082714       0.121036
2        0.362797       0.334152  ...       0.074653       0.090501
3        0.236709       0.267264  ...       0.059940       0.067564
4        0.295526       0.290872  ...       0.084341       0.092015
5        0.260988       0.297404  ...       0.076164       0.076678
6        0.203717       0.257175  ...       0.088583       0.113014
7        0.240343       0.316101  ...       0.086066       0.111023
8        0.217410       0.256307  ...       0.086746       0.055840
9        0.249015       0.248200  ...       0.078539       0.081257
10       0.125692       0.275354  ...       0.069692       0.120021
11       0.174843       0.229359  ...       0.086379       0.092276
12       0.214966       0.181651  ...       0.123152       0.086036
13       0.204998       0.208303  ...       0.074675       0.066737
14       0.189747       0.233315  ...       0.118229       0.167469
15       0.208187       0.364784  ...       0.099169       0.141607
16       0.270985       0.215675  ...       0.073028       0.084740
17       0.224868       0.228776  ...       0.070842       0.108148
18       0.287401       0.219324  ...       0.068044       0.116148
19       0.163602       0.232492  ...       0.062264       0.120547

[20 rows x 24 columns]

In [ ]:
start_time = time.process_time()
mfccs_means = []
mfccs_stds = []

for i in range(len(df)):
  mfccs=librosa.feature.mfcc(y=df['y'][i], sr=sr, n_mfcc=13)
  mfccs_mean=np.mean(mfccs,axis=1)
  mfccs_std=np.std(mfccs,axis=1)
  mfccs_means.append(mfccs_mean)
  mfccs_stds.append(mfccs_std)

mfccs_df = pd.DataFrame()
for j in range(len(df)):
  for i in range(0,13):
      mfccs_df['mfccs_mean_'+str(i)]=mfccs_means[j][i]
  for i in range(0,13):
      mfccs_df['mfccs_std_'+str(i)]=mfccs_means[j][i]

for t in range(len(df)):
  mfccs_df.loc[t]=np.concatenate((mfccs_means[t],mfccs_stds[t]),axis=0)

print("The whole process took", time.process_time() - start_time, "seconds.")
mfccs_df

The whole process took 9.950578215000007 seconds.

    mfccs_mean_0  mfccs_mean_1  ...  mfccs_std_11  mfccs_std_12
0     -37.519196     59.437370  ...      6.189720      5.554039
1     -82.019508     91.530914  ...      5.571157      5.531799
2     -66.298111    100.776901  ...      5.582160      5.746347
3     -94.127022    100.757957  ...      6.473011      6.011395
4    -126.050156    112.837112  ...      5.903671      6.329760
5     -81.188820     99.699081  ...      6.253897      6.457817
6     -16.145885     91.852242  ...      5.843176      5.915280
7     -65.398285     85.596848  ...      6.529060      6.468457
8       9.668294     85.227005  ...      6.229192      5.612007
9     -14.024172     96.755310  ...      6.442915      6.444199
10    -48.739243     82.003021  ...      6.560354      5.924997
11    -84.007088     80.274765  ...      7.470662      6.664783
12   -132.530334     93.285439  ...      5.656878      5.703158
13    -25.478464     88.568184  ...      6.148547      5.673187
14    -54.810493     68.677299  ...      5.639904      5.461400
15    -73.213936     76.782074  ...      5.850677      6.872397
16    -90.011368     67.025269  ...      7.474687      7.016637
17    -34.475441     68.640968  ...      5.355911      5.182124
18     -3.592725     58.033733  ...      5.712569      6.060236
19      4.210250     78.372520  ...      4.923288      5.173893

[20 rows x 26 columns]

In [ ]:
from scipy import stats
start_time = time.process_time()
centroid_means = []
centroid_stds = []
centroid_skews = []

for i in range(len(df)):
  centroid=librosa.feature.spectral_centroid(y=df['y'][i], sr=sr)
  centroid_mean=np.mean(centroid,axis=1)
  centroid_std=np.std(centroid,axis=1)
  centroid_means.append(centroid_mean)
  centroid_stds.append(centroid_std)
  cent_skew=stats.skew(centroid,axis=1)[0]
  centroid_skews.append(cent_skew)

centroid_df = pd.DataFrame()

centroid_df['centroid_mean'] = centroid_means
centroid_df['centroid_std'] = centroid_stds
centroid_df['centroid_skews'] = centroid_skews

centroid_df

           centroid_mean          centroid_std  centroid_skews
0     [3241.64701244363]   [882.3772951315154]        0.794806
1   [2215.5423393216793]    [592.767387274822]       -1.455516
2   [2213.3294348509553]   [540.7411562758911]        1.682564
3   [2251.0383135433403]   [635.0504056854253]        4.146112
4   [2047.1573821300071]   [624.4874449945429]       -0.034139
5    [2195.112012597551]  [420.20578356734666]       -0.464574
6   [2316.0361100114383]  [497.39516062669355]        2.557374
7   [2496.7581392925076]   [916.2455016710837]        0.858949
8    [2512.618370993558]   [592.5729858707042]        0.819409
9    [2291.761252314791]  [369.50170045790014]       -0.337976
10  [2569.5587865597536]   [514.3184727957986]        0.732957
11   [2468.607317345308]   [715.6952511797167]        0.373640
12  [2367.6628853520056]    [652.404287514067]       -0.318933
13   [2424.051075112304]   [472.0200309715749]        0.549669
14  [2716.1844260536977]   [720.0946829391842]       -0.163311
15  [2395.7415973893735]   [799.1379746304023]       -0.404115
16  [2690.4993522182285]   [926.5314300181868]        0.448467
17  [2770.8142326498996]   [675.6486569101389]       -1.294374
18  [3203.2877945279406]    [606.183766372769]       -1.125644
19  [2858.9390334299364]   [588.0649156195516]       -0.186501

In [ ]:
contrast_means = []
contrast_stds = []

for i in range(len(df)):
  contrast=librosa.feature.spectral_contrast(y=df['y'][i], sr=sr)
  contrast_mean=np.mean(contrast,axis=1)
  contrast_std=np.std(contrast,axis=1)
  contrast_means.append(contrast_mean)
  contrast_stds.append(contrast_std)

contrast_df = pd.DataFrame()

contrast_df['contrast_mean'] = contrast_means
contrast_df['contrast_std'] = contrast_stds

contrast_df

                                        contrast_mean                                       contrast_std
0   [21.532382356438298, 13.247388984139478, 15.41...  [4.62278572581887, 3.4957556772778173, 3.58927...
1   [21.45738072846245, 13.461631597768706, 15.770...  [4.838148514995893, 3.8290798283211247, 3.7536...
2   [20.715287546669177, 13.23733824677447, 15.966...  [4.725013654689759, 3.6171657688015553, 3.9692...
3   [21.35726377310757, 13.414404455822977, 16.581...  [4.648339835872314, 3.8809546318836787, 4.0382...
4   [21.647631545327776, 13.057110733870882, 16.35...  [4.755886883654328, 3.6612492808857002, 4.0726...
5   [21.660926613977733, 13.11206958599993, 16.587...  [4.659566768690623, 3.975833532886056, 4.26888...
6   [20.892315028749383, 14.061218414311233, 17.49...  [4.516079657845712, 3.9070489921271103, 4.7378...
7   [20.516086615324554, 14.285879927813447, 15.86...  [4.516743727773123, 3.7415597584813383, 3.5899...
8   [20.610304019344486, 14.833147219966602, 17.42...  [4.749550664535144, 4.4716294346382055, 4.7055...
9   [20.84938611149535, 14.530597094936056, 17.910...  [4.667897668378911, 3.7542256704831884, 4.0198...
10  [22.17174417505721, 13.616482356364394, 18.730...  [4.560306316416554, 3.815177799059067, 4.19498...
11  [23.02526900286986, 15.15431516372429, 17.6691...  [4.875110871421256, 4.249280806645378, 4.63275...
12  [18.039325438001388, 14.281392028141557, 17.03...  [4.309271658364179, 4.06710956677966, 4.130166...
13  [20.925450299998037, 14.59771421311488, 15.752...  [4.576619021308297, 3.927122287673601, 3.70954...
14  [20.373625288674646, 16.12520062977691, 17.069...  [4.630941852247258, 3.808324220667353, 4.14800...
15  [21.138628603169806, 16.411660354824427, 16.07...  [4.817649460715357, 4.530880926854312, 4.05332...
16  [20.35536745251944, 14.894501575581224, 18.046...  [4.896446346797038, 4.812568169230378, 4.91462...
17  [22.015155280324475, 13.955709521580559, 15.88...  [5.031783501923922, 3.775900775081331, 4.33721...
18  [21.343943989044924, 15.049527034280958, 17.87...  [4.637533423318936, 3.818235684301188, 4.12427...
19  [16.507915015389525, 12.631218279791614, 14.83...  [4.688090764772614, 3.452777048034907, 3.41179...

In [ ]:
contrast_df["contrast_std"][0]

array([4.62278573, 3.49575568, 3.58927311, 2.86457776, 2.26100298,
       1.97743321, 3.18783865])

In [ ]:
roll_off_means = []
roll_off_stds = []
roll_off_skews = []

for i in range(len(df)):
  roll_off=librosa.feature.spectral_rolloff(y=df['y'][i], sr=sr)
  roll_off_mean=np.mean(roll_off,axis=1)
  roll_off_std=np.std(roll_off,axis=1)
  roll_off_means.append(roll_off_mean)
  roll_off_stds.append(roll_off_std)
  roll_off_skew=stats.skew(roll_off,axis=1)[0]
  roll_off_skews.append(roll_off_skew)

roll_off_df = pd.DataFrame()

roll_off_df['roll_off_mean'] = roll_off_means
roll_off_df['roll_off_std'] = roll_off_stds
roll_off_df['roll_off_skew'] = roll_off_skews

roll_off_df

           roll_off_mean          roll_off_std  roll_off_skew
0    [6471.248539261136]  [1425.6959281444801]      -0.388041
1    [5144.059702991126]  [1261.5300913251074]      -2.558312
2    [4838.115278719412]   [914.6542408291563]      -0.981277
3   [4362.6535625965425]  [1263.8337431588343]       1.897406
4   [4081.5170537733948]   [1484.399216905852]       0.321062
5    [4151.149876576929]   [986.2269676750377]       0.442345
6    [4556.939743750225]  [1131.1567391990618]       1.545965
7    [4761.180293270558]  [1647.4437775538158]       0.319464
8    [4890.942171992402]  [1142.5689379018204]       0.603763
9    [4233.662288298439]    [740.420839485416]       0.375470
10   [5380.552524667482]  [1244.2643369606647]       0.096209
11   [5187.739745094766]  [1556.9394733747476]      -0.756438
12   [5289.926677760203]  [1453.8189135341813]      -1.128598
13   [5103.844388736892]  [1043.1354505995873]       0.373666
14   [5734.913926862272]  [1560.9377544741155]      -0.406631
15   [5050.026704312266]  [1638.2682342965957]      -0.802010
16   [5039.014446099528]  [1672.5370844440747]      -0.042327
17   [5886.686710277044]  [1500.3264409293738]      -1.349583
18   [6427.210647391475]  [1129.8154268863395]      -2.048838
19   [6399.663987018653]  [1196.3707560625664]      -1.151760

In [ ]:
zero_means = []
zero_stds = []
zero_skews = []

for i in range(len(df)):
  zero=librosa.feature.zero_crossing_rate(df['y'][i])
  zero_mean=np.mean(zero,axis=1)
  zero_std=np.std(zero,axis=1)
  zero_means.append(zero_mean)
  zero_stds.append(zero_std)
  zero_skew=stats.skew(zero,axis=1)[0]
  zero_skews.append(zero_skew)

zero_df = pd.DataFrame()

zero_df['zero_mean'] = zero_means
zero_df['zero_std'] =zero_stds
zero_df['zero_skew'] = zero_skews

zero_df

                zero_mean                zero_std  zero_skew
0   [0.19579817815127126]   [0.09258878463465706]   1.417834
1   [0.08683380644561986]   [0.03858720521498427]   1.041428
2   [0.10789527623612513]   [0.05293785104145334]   3.531244
3   [0.11395155371217522]   [0.06421566085576491]   5.114811
4   [0.09897156719963643]  [0.038899013946575564]   0.417902
5   [0.12084547594753188]   [0.03201331376044039]   0.072822
6   [0.12495291899428797]  [0.046608058686485564]   3.948563
7    [0.1462500550918261]   [0.08019382684714023]   1.386167
8   [0.14018950591216217]   [0.05226483640781787]   0.845946
9   [0.14708197111865223]   [0.03453289565327609]  -0.344293
10   [0.1227977884429867]   [0.03658582795582657]   1.237845
11  [0.10979335235991135]  [0.049330587134649356]   2.039275
12  [0.09581719952294873]   [0.04438977455331888]   1.214685
13  [0.10963357888900743]   [0.03960893481860996]   1.172204
14  [0.11633812518648366]  [0.056660449612571495]   0.439584
15  [0.09872350639071295]   [0.06485471952690583]   0.817274
16   [0.1503228324777286]   [0.08167610789532112]   0.900425
17   [0.1298895474137931]   [0.04844557431653687]   0.224169
18  [0.17301097165065515]   [0.05218054265883182]   0.242421
19  [0.14748408752080253]  [0.051770074740704844]   1.429152

In [ ]:
tempos = []
frames = []
for j in range(len(df)):
  tempo, beat = librosa.beat.beat_track(y=df['y'][j], sr=sr)
  tempos.append(tempo)
  frames.append(beat)

beat_df = pd.DataFrame()

beat_df['tempo'] = tempos
beat_df['frame'] =frames
beat_df

         tempo                                              frame
0    89.102909  [16, 40, 63, 92, 121, 150, 180, 209, 238, 268,...
1   161.499023  [11, 30, 47, 62, 80, 97, 114, 130, 144, 157, 1...
2   161.499023  [8, 24, 42, 58, 71, 85, 99, 115, 131, 147, 164...
3   107.666016  [42, 66, 89, 111, 134, 157, 180, 203, 227, 250...
4   117.453835  [15, 35, 57, 79, 102, 124, 145, 165, 185, 206,...
5    95.703125  [15, 42, 68, 94, 119, 144, 170, 196, 219, 245,...
6   172.265625  [10, 26, 42, 58, 73, 88, 103, 117, 132, 147, 1...
7    89.102909  [13, 41, 69, 97, 125, 153, 182, 210, 239, 268,...
8   112.347147  [7, 32, 56, 73, 96, 120, 137, 160, 184, 201, 2...
9   103.359375  [5, 28, 53, 76, 100, 125, 150, 174, 200, 224, ...
10  117.453835  [12, 33, 54, 76, 97, 119, 141, 162, 183, 205, ...
11   99.384014  [13, 38, 64, 93, 118, 143, 167, 193, 221, 245,...
12  172.265625  [4, 19, 35, 51, 67, 83, 98, 113, 127, 141, 156...
13   99.384014  [3, 31, 60, 90, 119, 144, 170, 197, 223, 250, ...
14   92.285156  [4, 30, 58, 88, 118, 147, 176, 205, 234, 263, ...
15  184.570312  [24, 38, 52, 66, 80, 93, 107, 121, 135, 149, 1...
16  151.999081  [11, 28, 45, 62, 79, 95, 112, 128, 144, 161, 1...
17  107.666016  [11, 34, 57, 78, 100, 123, 145, 168, 196, 221,...
18  123.046875  [12, 35, 56, 79, 101, 120, 139, 159, 177, 196,...
19  103.359375  [5, 23, 49, 76, 102, 129, 156, 182, 209, 235, ...

In [ ]:
beat_df["frame"][0]

array([  16,   40,   63,   92,  121,  150,  180,  209,  238,  268,  297,
        327,  356,  385,  415,  444,  473,  502,  531,  560,  589,  619,
        648,  677,  706,  735,  764,  794,  822,  851,  881,  910,  939,
        968,  997, 1026, 1055, 1084, 1113, 1143, 1172, 1202, 1231, 1261,
       1289, 1318, 1346, 1376, 1404, 1435, 1464, 1494, 1522, 1551, 1581,
       1610, 1640, 1672, 1702, 1731, 1761, 1790, 1820, 1849, 1879, 1909,
       1939, 1968, 1997, 2027, 2057, 2086, 2116, 2145, 2175, 2204, 2233,
       2261, 2291, 2320, 2350, 2379, 2408, 2437, 2467, 2496, 2526, 2554,
       2584, 2613, 2643, 2672, 2701, 2731, 2760, 2789, 2818, 2849, 2879,
       2908, 2937, 2966, 2995, 3025, 3054, 3085, 3114, 3144, 3172, 3201,
       3230, 3261, 3289, 3320, 3350, 3379, 3409, 3438, 3467, 3497, 3527,
       3557, 3586, 3615, 3644, 3674, 3703, 3733, 3762, 3792, 3822, 3852,
       3881, 3911, 3940, 3970, 4000, 4030, 4059, 4089, 4118, 4148, 4177,
       4207, 4237, 4267, 4297, 4327, 4357, 4386, 4415, 4445, 4474, 4504,
       4534, 4564, 4593, 4622])

In [ ]:
len(beat_df["frame"][0])

158

**NLP Part**

In [ ]:
lyrics = pd.read_csv('/content/drive/MyDrive/dataset/classic punk/' + matching[0], index_col=False, header=None)

In [ ]:
lyrics = lyrics[:20]
lyrics = lyrics[0]
lyrics

0     make things worse sometimes rather die tell lo...
1     banned dc thousand places go gon na swim acros...
2     nt want anymore walked right door play game ri...
3     jealous cowards try control rise gon na rise d...
4     got six pack nothing got six pack nt need thir...
5     tv party tonight tv party tonight tv party ton...
6     spurn natural emotions make feel dirt hurt sta...
7     nt need anyone nt need mom dad nt need pretty ...
8     governor jerry brown aura smiles never frowns ...
9     school year two know seen daddy car thinkin go...
10    ca nt see torture already thinking someone els...
11    want stereotyped want classified wan na stereo...
12    something way taste makes want clear throat me...
13    yeah yeah yeah yeah yeahyeahyeahyeahyeahyeahye...
14    ca nt better start ca nt time running running ...
15    patient boy wait wait wait wait time like wate...
16    change good always knew would sometimes thinki...
17    lexicon devil battered brain searching future ...
18    curious know exactly keep distance distance fa...
19    comes johnny yen liquor drugs flesh machine go...
Name: 0, dtype: object

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [ ]:
mood = []
print("Negative  -   Positive")
for i in range(len(lyrics)):
    lyrical = lyrics[i]
    print(sid.polarity_scores(lyrical)['neg'] , "      ", sid.polarity_scores(lyrical)['pos'] )
    if(sid.polarity_scores(lyrical)['pos'] - sid.polarity_scores(lyrical)['neg'] > 0.05 ):
        truth = 1
        mood.append(truth)
    else:
        truth = 0
        mood.append(truth)

Negative  -   Positive
0.282        0.145
0.238        0.073
0.043        0.256
0.297        0.106
0.217        0.111
0.111        0.212
0.293        0.485
0.208        0.099
0.12        0.095
0.124        0.23
0.129        0.178
0.159        0.149
0.037        0.4
0.23        0.292
0.439        0.06
0.049        0.094
0.038        0.363
0.226        0.038
0.235        0.29
0.051        0.259

In [ ]:
nlp_df = pd.DataFrame(data = mood, columns = ["Sentiment"])
nlp_df

    Sentiment
0           0
1           0
2           1
3           0
4           0
5           1
6           1
7           0
8           0
9           1
10          0
11          0
12          1
13          1
14          0
15          0
16          1
17          0
18          1
19          1

In [ ]:
total_df = pd.concat([chroma_df, mfccs_df, centroid_df, contrast_df, roll_off_df, zero_df, beat_df, nlp_df], axis=1)

In [ ]:
total_df

    chroma_mean_0  ...  Sentiment
0        0.356904  ...          0
1        0.349846  ...          0
2        0.362797  ...          1
3        0.236709  ...          0
4        0.295526  ...          0
5        0.260988  ...          1
6        0.203717  ...          1
7        0.240343  ...          0
8        0.217410  ...          0
9        0.249015  ...          1
10       0.125692  ...          0
11       0.174843  ...          0
12       0.214966  ...          1
13       0.204998  ...          1
14       0.189747  ...          0
15       0.208187  ...          0
16       0.270985  ...          1
17       0.224868  ...          0
18       0.287401  ...          1
19       0.163602  ...          1

[20 rows x 64 columns]